# Generated by Django 4.2.1 on 2023-06-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('ano_lancamento', models.IntegerField()),
                ('diretor', models.CharField(max_length=128)),
                ('genero', models.CharField(max_length=50)),
                ('globo_ouro', models.IntegerField()),
                ('oscar', models.IntegerField()),
                ('nota', models.FloatField()),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
    ]
